from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

urlpatterns = [
    path('agregapasteleria/<nombre>/<descripcion>/<precio>', pasteleria),
    path('agregacocina/<nombre>/<descripcion>/<precio>', cocina),
    path('agregapromociones/<nombre>/<descripcion>/<precio>', promociones),
    path('listapasteleria/', lista_pasteleria, name="listadoPasteleria"),
    path('listacocina/', lista_cocina, name="listaCocina"),
    path('listapromociones/',lista_promociones, name="ListaPromociones"),
    path('', inicio, name="Inicio"),
    path('pasteleria/', pasteleria, name="Pastelería"),
    path('cocina/', cocina, name="Cocina"),
    path('promociones/', promociones, name="Promociones"),
    path('iniciar-sesion/', inicio_de_sesion, name="Iniciar sesión"),
    path('pasteleriaFormulario/', pasteleriaFormulario, name="pasteleriaFormulario"),
    path('cocinaFormulario/', cocinaFormulario, name="cocinaFormulario"),
    path('promocionesFormulario/', promocionesFormulario, name="promocionesFormulario"),
    path('busquedaPasteleria/', busquedaPasteleria, name="BusquedaPasteleria"),
    path('buscarPasteleria/', buscar_pasteleria, name="BuscandoPasteleria"),
    path('busquedaCocina/', busquedaCocina, name="BusquedaCocina"),
    path('buscarCocina/', buscar_cocina, name="BuscandoCocina"),
    path('busquedaPromociones/', busquedaPromociones, name="BusquedaPromociones"),
    path('buscarPromociones/', buscar_promociones, name="BuscandoPromociones"),
    path('listadoPasteleria/', PasteleriaList.as_view(), name="ListadoPasteleria"),
    path('detallePasteleria/<pk>', PasteleriaDetail.as_view(), name="DetallePasteleria"),
    path('creaPasteleria/', PasteleriaCreate.as_view(), name="CreaPasteleria"),
    path('actualizarPasteleria/<pk>', PasteleriaUpdate.as_view(), name="ActualizarPasteleria"),
    path('eliminaPasteleria/<pk>', PasteleriaDelete.as_view(), name="EliminaPasteleria"),
    path('listadoCocina/', CocinaList.as_view(), name="ListadoCocina"),
    path('detalleCocina/<pk>', CocinaDetail.as_view(), name="DetalleCocina"),
    path('creaCocina/', CocinaCreate.as_view(), name="CreaCocina"),
    path('actualizarCocina/<pk>', CocinaUpdate.as_view(), name="ActualizarCocina"),
    path('eliminaCocina/<pk>', CocinaDelete.as_view(), name="EliminaCocina"),
    path('listadoPromociones/', PromocionesList.as_view(), name="ListadoPromociones"),
    path('detallePromociones/<pk>', PromocionesDetail.as_view(), name="DetallePromociones"),
    path('creaPromociones/', PromocionesCreate.as_view(), name="CreaPromociones"),
    path('actualizarPromociones/<pk>', PromocionesUpdate.as_view(), name="ActualizarPromociones"),
    path('eliminaPromociones/<pk>', PromocionesDelete.as_view(), name="EliminaPromociones"),
    path('login/', loginView, name="Login"),
    path('register/', register, name="Registrar"),
    path('logout/', LogoutView.as_view(template_name= "logout.html"), name="Logout"),
    path('editarPerfil/', editar_perfil, name="EditarPerfil"),
    path('agregarAvatar/', agregar_avatar, name="AgregarAvatar"),
    path('creaUsuario/', crea_usuario, name="CreaUsuario"),
    path('pedidoiaPasteleria/', pedidoPasteleria, name="PedidoPasteleria"),
    path('pedidoiaCocina/', pedidoCocina, name="PedidoCocina"),
    path('pedidoiaPromociones/', pedidoPromociones, name="PedidoPromociones"),
    path('nosotros/', nosotros, name="Nosotros"),
    path('contacto/', contacto, name="Contacto"),
]
