# Generated by Django 4.2.5 on 2023-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0003_promociones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocina',
            name='creado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pasteleria',
            name='creado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='promociones',
            name='creado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
