# Generated by Django 4.2.4 on 2023-10-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0004_cocina_creado_pasteleria_creado_promociones_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocina',
            options={'verbose_name': 'Cocina'},
        ),
        migrations.AlterModelOptions(
            name='pasteleria',
            options={'verbose_name': 'Pastelería'},
        ),
        migrations.AlterModelOptions(
            name='promociones',
            options={'verbose_name': 'Promoción'},
        ),
    ]
