# Generated by Django 4.2.4 on 2023-10-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0008_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=10)),
                ('comentario', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Pedidos',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
